//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace txtnote.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("txtnote.Resources.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string addImage {
            get {
                return ResourceManager.GetString("addImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add txt file 的本地化字符串。
        /// </summary>
        public static string addtxt {
            get {
                return ResourceManager.GetString("addtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change background image 的本地化字符串。
        /// </summary>
        public static string background {
            get {
                return ResourceManager.GetString("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string bangzhu {
            get {
                return ResourceManager.GetString("bangzhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string baocun {
            get {
                return ResourceManager.GetString("baocun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeed 的本地化字符串。
        /// </summary>
        public static string chenggong {
            get {
                return ResourceManager.GetString("chenggong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to select or replace pictures 的本地化字符串。
        /// </summary>
        public static string chooseimage {
            get {
                return ResourceManager.GetString("chooseimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create time 的本地化字符串。
        /// </summary>
        public static string chuangjian {
            get {
                return ResourceManager.GetString("chuangjian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact  的本地化字符串。
        /// </summary>
        public static string contactwritter {
            get {
                return ResourceManager.GetString("contactwritter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string daoru {
            get {
                return ResourceManager.GetString("daoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the file in merge folder is not encoded by UTF-8,please change the encoding way on computer,press OK Button to continue！ 的本地化字符串。
        /// </summary>
        public static string download_1 {
            get {
                return ResourceManager.GetString("download_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download finished! 的本地化字符串。
        /// </summary>
        public static string download_2 {
            get {
                return ResourceManager.GetString("download_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files in Skydrive\txtNote : 的本地化字符串。
        /// </summary>
        public static string downloadtitle {
            get {
                return ResourceManager.GetString("downloadtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit txt file 的本地化字符串。
        /// </summary>
        public static string edittxt {
            get {
                return ResourceManager.GetString("edittxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share 的本地化字符串。
        /// </summary>
        public static string fenxiang {
            get {
                return ResourceManager.GetString("fenxiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the txt name 的本地化字符串。
        /// </summary>
        public static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string gailan {
            get {
                return ResourceManager.GetString("gailan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work 的本地化字符串。
        /// </summary>
        public static string gongzuo {
            get {
                return ResourceManager.GetString("gongzuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 link 的本地化字符串。
        /// </summary>
        public static string guanlian {
            get {
                return ResourceManager.GetString("guanlian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search All 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.Press the input box for long time to change the cursor position accurately;
        ///
        ///2.When &quot;Search All&quot; selected,both content and name of txt files will be searched;
        ///
        ///3.You can easily upload or download txt files by &quot;Share Page&quot;;
        ///
        ///4.In Skydrive,the default folder is &quot;txtNote&quot;,and merged file is saved in &quot;Merge&quot; folder;
        ///
        ///5.When using &quot;Import Page&quot;,name and content is divided by &quot;Tab&quot; in txt file ,so you can copy the Excel table and save as txt files in &quot;Merge&quot; folder with UTF-8; 的本地化字符串。
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to select the binding txt 的本地化字符串。
        /// </summary>
        public static string imagename {
            get {
                return ResourceManager.GetString("imagename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files in Skydrive\txtNote\Merge : 的本地化字符串。
        /// </summary>
        public static string importtitle {
            get {
                return ResourceManager.GetString("importtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string mingcheng {
            get {
                return ResourceManager.GetString("mingcheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to go back without saving it? 的本地化字符串。
        /// </summary>
        public static string okBack {
            get {
                return ResourceManager.GetString("okBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by 的本地化字符串。
        /// </summary>
        public static string paixufangshi {
            get {
                return ResourceManager.GetString("paixufangshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluate 的本地化字符串。
        /// </summary>
        public static string pingjia {
            get {
                return ResourceManager.GetString("pingjia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin to Start 的本地化字符串。
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean 的本地化字符串。
        /// </summary>
        public static string qingchu {
            get {
                return ResourceManager.GetString("qingchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Cat. 的本地化字符串。
        /// </summary>
        public static string quanbu {
            get {
                return ResourceManager.GetString("quanbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string quanxuan {
            get {
                return ResourceManager.GetString("quanxuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string richang {
            get {
                return ResourceManager.GetString("richang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search something here 的本地化字符串。
        /// </summary>
        public static string searchBox {
            get {
                return ResourceManager.GetString("searchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language(effect after restart the app) 的本地化字符串。
        /// </summary>
        public static string setting_1 {
            get {
                return ResourceManager.GetString("setting_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string shanchu {
            get {
                return ResourceManager.GetString("shanchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not signed in，please click &quot;sign in&quot; 的本地化字符串。
        /// </summary>
        public static string shareInfo_1 {
            get {
                return ResourceManager.GetString("shareInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 signed in 的本地化字符串。
        /// </summary>
        public static string shareInfo_2 {
            get {
                return ResourceManager.GetString("shareInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to upload. 的本地化字符串。
        /// </summary>
        public static string shareInfo_3 {
            get {
                return ResourceManager.GetString("shareInfo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community share 的本地化字符串。
        /// </summary>
        public static string shareInfo_4 {
            get {
                return ResourceManager.GetString("shareInfo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge  的本地化字符串。
        /// </summary>
        public static string shareInfo_5 {
            get {
                return ResourceManager.GetString("shareInfo_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to upload? txt file of the same name will overwrite the file once uploaded! 的本地化字符串。
        /// </summary>
        public static string shareInfo_6 {
            get {
                return ResourceManager.GetString("shareInfo_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to download? txtfile of the same name will overwrite the file existed! 的本地化字符串。
        /// </summary>
        public static string shareInfo_7 {
            get {
                return ResourceManager.GetString("shareInfo_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string shezhi {
            get {
                return ResourceManager.GetString("shezhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an example,add the explanation here. 的本地化字符串。
        /// </summary>
        public static string shili {
            get {
                return ResourceManager.GetString("shili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload  的本地化字符串。
        /// </summary>
        public static string skydrive {
            get {
                return ResourceManager.GetString("skydrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to exit txtNote? 的本地化字符串。
        /// </summary>
        public static string tuichu {
            get {
                return ResourceManager.GetString("tuichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 files ready to upload to SkyDrive： 的本地化字符串。
        /// </summary>
        public static string upload_1 {
            get {
                return ResourceManager.GetString("upload_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string xiazai {
            get {
                return ResourceManager.GetString("xiazai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hobbies 的本地化字符串。
        /// </summary>
        public static string xingqu {
            get {
                return ResourceManager.GetString("xingqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit time 的本地化字符串。
        /// </summary>
        public static string xiugai {
            get {
                return ResourceManager.GetString("xiugai", resourceCulture);
            }
        }
    }
}
